version: '3.8'

services:
  ecommerce-postgres-container:
    image: postgres:14
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/Projects/docker/mysql/ecommerce-data-postgres:/var/lib/postgresql/data